const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const gameSchema = new Schema({
    rawgid: Number,
    title: String,
    img: {
        type: String,
        default: "https://www.ipsgroup.fr/wp-content/uploads/2013/12/default_image_01.png",
    },
    ratings: { type: Number, min: 0, max: 100 },
    genres: {
        type: [String],
        enum: [
            "Action",
            "Indie",
            "Adventure",
            "RPG",
            "Strategy",
            "Shooter",
            "Casual",
            "Simulation",
            "Puzzle",
            "Arcade",
            "Platformer",
            "Racing",
            "Sports",
            "Massively Multiplayer",
            "Family",
            "Fighting",
            "Board Games",
            "Educational",
            "Card",
        ],
    },
    plateform: {
        type: [String],
        enum: [
            "PlayStation 5",
            "PlayStation 4",
            "PlayStation 3",
            "PlayStation 2",
            "PlayStation",
            "Xbox One",
            "Xbox Series S/X",
            "Xbox 360",
            "Xbox",
            "PC",
            "Steam",
            "Mobile",
            "PSP",
            "PS Vita",
            "Nintendo DS",
            "Nintendo WII",
            "Nintendo Switch",
            "macOS",
            "Linux",
            "Android",
            "iOS",
            "Web",
            "Wii U",
            "Nintendo 3DS",
            "Classic Macintosh",
            "Wii",
            "GameCube",
            "Genesis",
            "SNES",
            "Game Boy",
            "Game Gear",
            "SEGA Master System",
            "SEGA CD",
            "Commodore / Amiga",
            "Neo Geo",
            "Dreamcast",
            "Nintendo 64",
            "Game Boy Advance",
            "Game Boy Color",
            "Jaguar",
            "Apple II",
            "Nintendo DSi",
            "Genesis",
            "SNES",
            "Game Gear",
            "SEGA Saturn",
            "3DO",
            "NES",
            "Atari 8-bit",
            "Atari ST",
            "Atari Lynx",
            "SEGA 32X",
            "Atari 5200",
            "Atari 2600",
            "Atari 7800",
            "Atari XEGS",
            "Atari Flashback"
        ],
    },
    screenshots: [String],
    videos: String
});

const Game = mongoose.model("Games", gameSchema);

module.exports = Game;